### ISSUE TITLE
App immediately crashes when joining call (targeting android API version 31)

### ISSUE THREAD

**Issue by raymondpebble** [daily-co/react-native-daily-js#25]
# Expected behavior

No crash / exception.

# Describe the bug (unexpected behavior)

```
Unable to start service com.daily.reactlibrary.DailyOngoingMeetingForegroundService@c6d9368 with Intent { cmp=_____/com.daily.reactlibrary.DailyOngoingMeetingForegroundService (has extras) }: java.lang.IllegalArgumentException: ______: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
```

# Steps to reproduce

- Set react native project to target android API version 31
- Run on a physical device running android 12
- Try to join a daily call
- Immediately crashes

# System information 

 

* Device: Samsung S10, Pixel 5a
* OS, version: Android 12

**Comment by filipi87** [comment]
Hi @raymondpebble 

This issue has been fixed on our latest version of react-native-daiy-js, 0.24.0.

We have added support for Android 12. You can see the release notes here: https://github.com/daily-co/react-native-daily-js/releases

**Comment by vineetk242000** [comment]
Hi @filipi87 
I am still having the same issue on Android 12. The app crashes once call join method is invoked in Android. I have attached the snippet of the terminal as the error message keeps repeating after join method.
![carbon](https://user-images.githubusercontent.com/57609127/191201858-0b91787b-65e5-480c-a63b-3dd515e13360.png)

**Comment by filipi87** [comment]
Hi @vineetk242000 ,

This looks like a completely different issue. Could you open a ticket so we can investigate that, would be nice to also add more information about your environment, like which version of `react-native-daily-js` you are using.

At first glance, looking at the error, I found It curious, because we have two possible listeners:
- [joining-meeting](https://docs.daily.co/reference/rn-daily-js/events/meeting-events#joining-meeting)
- [joined-meeting](https://docs.daily.co/reference/rn-daily-js/events/meeting-events#joined-meeting)

And the error says just `join-meeting`.

If you are trying to use some listeners, please also add on the ticket so I can try to reproduce it here.

Thanks a lot for your report.
